In [1]:
import numpy as np

In [28]:
import numpy.matlib

In [3]:
ceil = (56.3,5.2,15.3)

In [5]:
ceil

(56.3, 5.2, 15.3)

In [7]:
arre_ceil = np.ceil(ceil)

In [8]:
arre_ceil 

array([57.,  6., 16.])

In [9]:
fix = (23.2,98.0,235.4,3456.8)

In [12]:
arre_fix = np.fix (fix)

In [13]:
arre_fix

array([  23.,   98.,  235., 3456.])

In [14]:
floor = (23.2,98.0,235.4,3456.8)

In [15]:
floor

(23.2, 98.0, 235.4, 3456.8)

In [18]:
arre_floor = np.floor (floor)

In [19]:
arre_floor

array([  23.,   98.,  235., 3456.])

In [20]:
rint = (23.2,98.0,235.4,3456.8)

In [23]:
rint_arre = np.rint(rint)

In [26]:
rint

(23.2, 98.0, 235.4, 3456.8)

In [24]:
rint_arre

array([  23.,   98.,  235., 3457.])

In [33]:
eye_matlib = np.matlib.eye( 6 , k = 0 , dtype = float)

In [34]:
eye_matlib

matrix([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [35]:
identity = np.matlib.identity( 8 , int)

In [36]:
identity

matrix([[1, 0, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1]])

In [37]:
identity1 = np.matlib.identity( 8 )

In [38]:
identity1

matrix([[1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1.]])