In [66]:
import numpy as np

In [67]:
test_array = np.array ([55,44,33,66,88,11,99])

In [68]:
test_array

array([55, 44, 33, 66, 88, 11, 99])

In [69]:
print(type(test_array))

<class 'numpy.ndarray'>


In [70]:
type(test_array)

numpy.ndarray

In [119]:
test_array2 = np.array ([[55,44,33,66,88,11,99],[69,59,25,384,25],[59,685,41,44,45]])

In [120]:
test_array2

array([list([55, 44, 33, 66, 88, 11, 99]), list([69, 59, 25, 384, 25]),
       list([59, 685, 41, 44, 45])], dtype=object)

In [121]:
print(test_array2)

[list([55, 44, 33, 66, 88, 11, 99]) list([69, 59, 25, 384, 25])
 list([59, 685, 41, 44, 45])]


In [122]:
print(test_array2.ndim)

1


In [123]:
test_array.ndim

1

In [124]:
test_array.itemsize

8

In [125]:
print(test_array2.itemsize)

8


In [126]:
test_array.dtype

dtype('int64')

In [127]:
test_array.size

7

In [128]:
test_array2.size

3

In [129]:
test_array.shape

(7,)

In [130]:
test_array2.shape


(3,)

In [158]:
test_array3 = np.array([[56,58,44,62,39,87,],[75,28,36,69,14,],[55,66,42,39,10]])

In [159]:
test_array3

array([list([56, 58, 44, 62, 39, 87]), list([75, 28, 36, 69, 14]),
       list([55, 66, 42, 39, 10])], dtype=object)

In [160]:
test_array3.shape

(3,)

Arithmetic operations on array

In [167]:
array1 = np.array([[63,58,31,42],[65,24,36,25],[79,65,14,35],[0,0,0,0]])

In [168]:
array2 = np.array([[39,55,48,20],[36,47,14,48],[98,20,15,36],[98,20,15,36]])

In [170]:
array1 * array2

array([[2457, 3190, 1488,  840],
       [2340, 1128,  504, 1200],
       [7742, 1300,  210, 1260],
       [   0,    0,    0,    0]])

In [174]:
array1 / array2

array([[1.61538462, 1.05454545, 0.64583333, 2.1       ],
       [1.80555556, 0.5106383 , 2.57142857, 0.52083333],
       [0.80612245, 3.25      , 0.93333333, 0.97222222],
       [0.        , 0.        , 0.        , 0.        ]])

In [176]:
array1 // array2

array([[1, 1, 0, 2],
       [1, 0, 2, 0],
       [0, 3, 0, 0],
       [0, 0, 0, 0]])

In [177]:
array1 + array2

array([[102, 113,  79,  62],
       [101,  71,  50,  73],
       [177,  85,  29,  71],
       [ 98,  20,  15,  36]])

In [180]:
np.hstack((array1 , array2))

array([[63, 58, 31, 42, 39, 55, 48, 20],
       [65, 24, 36, 25, 36, 47, 14, 48],
       [79, 65, 14, 35, 98, 20, 15, 36],
       [ 0,  0,  0,  0, 98, 20, 15, 36]])

In [181]:
np.vstack((array1 , array2))

array([[63, 58, 31, 42],
       [65, 24, 36, 25],
       [79, 65, 14, 35],
       [ 0,  0,  0,  0],
       [39, 55, 48, 20],
       [36, 47, 14, 48],
       [98, 20, 15, 36],
       [98, 20, 15, 36]])