In [3]:
import numpy as np

In [27]:
l_zeros_int = np.zeros((6,9),dtype=int)

In [28]:
l_zeros_int

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
l_zeros_float  = np.zeros((6,9),dtype=float)

In [30]:
l_zeros_float

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [31]:
l_ones_int = np.ones((6,4),dtype=int)

In [32]:
l_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
l_ones_float = np.ones((6,4),dtype=float)

In [34]:
l_ones_float

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [56]:
array = np.empty((6,4),dtype=int)

In [57]:
array

array([[    140001366302048,            31262640,     140001367146824,
            140001368153872],
       [    140001298153904,     140001304372928,     140001332343728,
            140001302963960],
       [    140001368261552,     140001368261608,     140001368261664,
            140001367592328],
       [    140001368261776,     140001367163696, 8391155419785880946,
               366991471713],
       [8214565721656657193,      46669114638377, 6156983640574423552,
               130761621504],
       [   8851068603604594, 7955995078501728256,        791874073705,
         433471464134412403]])